### PR TITLE
Added mqtt plugin

### PR DESCRIPTION
**Pull request by tschmidty69**
appdaemon config

```yaml
    MQTT:
      type: mqtt
      verbose: True
      mqtt_client_host: 'MQTT_IP'
      mqtt_client_port: 1883
      mqtt_client_user: !secret mqtt_user
      mqtt_client_password: !secret mqtt_password
      mqtt_ca_cert: ca certficate used to verify broker
      mqtt_client_cert: mycert
      mqtt_client_key: mykey
      mqtt_verify_cert: false
      mqtt_client_topics:
        - hermes/intent/#
        - hermes/hotword/#
```
Example app to bridge to another app
app.yaml
```yaml
mqtt_demo:
  module: mqtt_demo
  class: mqtt_demo
  dependencies: jarvis_core
```
mqtt_demo.py
```
import appdaemon.plugins.mqtt.mqttapi as mqtt


class mqtt_demo(mqtt.Mqtt):

    def initialize(self):
        self.log("__function__: MQTT DEMO Listening")
        self.listen_event(self.mqtt_message,
                          'MQTT_MESSAGE')

    def mqtt_message(self, event_name, data, *args, **kwargs):
        self.log("__function__: %s" % data)

```

### CODE REVIEW

**Comment by uchagani** [comment]
👏 🎉

**Comment by acockburn** [comment]
I'll be merging this soon after the official 3,0 release :)

**Comment by uchagani** [comment]
any chance we can get this part of v3?

**Comment by acockburn** [comment]
No - I need to get 3.0 ASAP to address some problems in 2,x, and I will need to setup an MQTT server and do some minimal testing before I release this.

**Comment by tschmidty69** [comment]
Any chance to poke at this?

**Comment by acockburn** [comment]
I'll take a look at this probably at the weekend - I need to set up an MQTT server to test it.

**Comment by tschmidty69** [comment]
Since it is a listener and not a server really, you could test just using the mosquitto_pub client from mosquitto-clients. I could really use this to release a project I have going on.

**Comment by acockburn** [comment]
I took a look this weekend and will merge and do some testing next weekend (traveling on business this week). One question - why did you implement `listen_event()` rather than `listen_state()` for changes? I know they are kind of events but we are modeling this as a set of states for AD so it seems more logical to do a listen_state()

**Comment by acockburn** [comment]
By the way, if it helps, as of 3.0 you can add plugins by placing the plugin dir in a directory called `custom_plugins` in your config directory, so you don't need to edit the install or clone the repository to run your plugin before I release it.

**Comment by tschmidty69** [comment]
Mainly to mirror what I do with my HASS plugin, where I listen for events fired instead of triggering off states. States seem really awkward for what are essentially transient objects. You could obviously do it that way, but storing the state is unnecessary. The mqtt message is only valid at that point in time.

**Comment by acockburn** [comment]
OK, if that is the case, it seems incorrect to maintain the state in AD, would you agree?

**Comment by tschmidty69** [comment]
Yep. The get_state and set_state are just stubs, right? I am not sure what appdaemon is doing under the hood.

**Comment by tschmidty69** [comment]
Awesome on the custom plugins! That will work for my project.

**Comment by acockburn** [comment]
The reason for the set_state() in the plugin is so that apps can refer back to the state locally without a potentially expensive call back into the plugin - e.g. a REST call to HASS for example. IF we are just watching events however, then setting state is spurious so I can remove that call from the code, as well as the stubs since they don't do anything.

**Comment by tschmidty69** [comment]
Got this when poking at a standalone instance: 
```
/srv/jarvis/custom_plugins/mqtt/mqttplugin.py:77: RuntimeWarning: coroutine 'AppDaemon.state_update' was never awaited
  'payload': ''.join( chr(x) for x in msg.payload)}})
```
I'd also like to do a little more robust testing of connect. Right now it is failing somewhat silently with a bad username/password and I suppose TLS would be good to enable...

**Comment by tschmidty69** [comment]
Hmm, what is the syntax in the app for importing the mqtt plugin from custom_plugins. Got around it by copying it to plugins but still...

Sigh, I think the raspbian 3.5 is the issue here. Going to test with 3.6.

**Comment by acockburn** [comment]
As far as the app is concerned it should be the same as if it were part of
the distribution.

**Comment by tschmidty69** [comment]
So first thing I had to install the tag of appdaemon to get the basename to load the plugin correctly. I could have probably just done the dev branch but pip was being annoying
```pip3.6 install --upgrade git+https://github.com/home-assistant/appdaemon.git@465a9a5b7bca06c27e1f4d5679c67066183e2157v```

But then get this error:
```
2018-04-03 11:16:05.751783 INFO AppDaemon: Loading Custom Plugin MQTT using class MqttPlugin from module mqttplugin
2018-04-03 11:16:05.872276 INFO AppDaemon: MQTT Plugin Initializing
2018-04-03 11:16:05.875594 INFO AppDaemon: MQTT Plugin initialization complete
2018-04-03 11:16:05.876972 INFO Dashboards are disabled
2018-04-03 11:16:05.877701 INFO Starting API
2018-04-03 11:16:05.883656 INFO AppDaemon: Got initial state from namespace mqtt
2018-04-03 11:16:06.880734 INFO AppDaemon: MQTT: on_connect: subscribed: hermes/intent/#
2018-04-03 11:16:06.883645 INFO AppDaemon: MQTT: on_connect: subscribed: hermes/hotword/#
2018-04-03 11:16:06.886581 INFO AppDaemon: MQTT: on_connect: subscribed: hermes/asr/#
2018-04-03 11:16:07.207164 INFO AppDaemon: Reading config
2018-04-03 11:16:07.627952 WARNING AppDaemon: App 'intents' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.789850 WARNING AppDaemon: App 'True' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.791299 WARNING AppDaemon: App 'False' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.792077 WARNING AppDaemon: App 'ok' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.793128 WARNING AppDaemon: App 'sorry' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.794960 WARNING AppDaemon: App 'not_understood' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.796105 WARNING AppDaemon: App 'too_much_change' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.797035 WARNING AppDaemon: App 'set_temperature' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.797677 WARNING AppDaemon: App 'cant_set_temperature' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.798288 WARNING AppDaemon: App 'cant_do_yet' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.798878 WARNING AppDaemon: App 'turn_on_or_off' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.799436 WARNING AppDaemon: App 'already_state' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.800003 WARNING AppDaemon: App 'not_found' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.800729 WARNING AppDaemon: App 'unknown_entity' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.801357 WARNING AppDaemon: App 'greeting' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.801920 WARNING AppDaemon: App 'intent_not_recognized' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.802460 WARNING AppDaemon: App 'joke' missing 'class' or 'module' entry - ignoring
2018-04-03 11:16:07.803096 INFO AppDaemon: /srv/jarvis/apps/jarvis.yaml added or modified
2018-04-03 11:16:07.803675 INFO AppDaemon: /srv/jarvis/apps/mqtt_demo/mqtt_demo.yaml added or modified
2018-04-03 11:16:07.804176 INFO AppDaemon: /srv/jarvis/apps/jarvis_magic_door/jarvis_magic_door.yaml added or modified
2018-04-03 11:16:07.804660 INFO AppDaemon: /srv/jarvis/apps/jarvis_magic_door/intents.yaml added or modified
2018-04-03 11:16:07.805216 INFO AppDaemon: /srv/jarvis/apps/data/jarvis_en.yaml added or modified
2018-04-03 11:16:07.805858 INFO AppDaemon: /srv/jarvis/apps/jarvis.yaml added or modified
2018-04-03 11:16:07.806447 INFO AppDaemon: /srv/jarvis/apps/mqtt_demo/mqtt_demo.yaml added or modified
2018-04-03 11:16:07.807046 INFO AppDaemon: /srv/jarvis/apps/jarvis_magic_door/jarvis_magic_door.yaml added or modified
2018-04-03 11:16:07.807586 INFO AppDaemon: /srv/jarvis/apps/jarvis_magic_door/intents.yaml added or modified
2018-04-03 11:16:07.808085 INFO AppDaemon: /srv/jarvis/apps/data/jarvis_en.yaml added or modified
2018-04-03 11:16:07.808590 INFO AppDaemon: App 'jarvis_core' added
2018-04-03 11:16:07.809077 INFO AppDaemon: App 'mqtt_demo' added
2018-04-03 11:16:07.809564 INFO AppDaemon: App 'jarvis_magic_door' added
2018-04-03 11:16:07.810422 INFO AppDaemon: Adding /srv/jarvis/apps to module import path
2018-04-03 11:16:07.811392 INFO AppDaemon: Adding /srv/jarvis/apps/mqtt_demo to module import path
2018-04-03 11:16:07.812389 INFO AppDaemon: Adding /srv/jarvis/apps/jarvis_magic_door to module import path
2018-04-03 11:16:07.813339 INFO AppDaemon: Adding /srv/jarvis/apps/data to module import path
2018-04-03 11:16:07.816047 INFO AppDaemon: Loading App Module: /srv/jarvis/apps/jarvis_core.py
2018-04-03 11:16:07.876894 INFO AppDaemon: Loading App Module: /srv/jarvis/apps/mqtt_demo/mqtt_demo.py
2018-04-03 11:16:07.880708 WARNING AppDaemon: ------------------------------------------------------------
2018-04-03 11:16:07.881429 WARNING AppDaemon: Unexpected error loading module: /srv/jarvis/apps/mqtt_demo/mqtt_demo.py:
2018-04-03 11:16:07.882014 WARNING AppDaemon: ------------------------------------------------------------
2018-04-03 11:16:07.891224 WARNING AppDaemon: Traceback (most recent call last):
  File "/srv/jarvis/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2015, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/srv/jarvis/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1802, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
 ```

**Comment by tschmidty69** [comment]
Bummer even with 3.6 it is failing with the same coroutine error. The plugin gets the message but never sends the event (because I am not await the function so it never returns...)

I am not sure the best way to tackle it. Async always gives me headaches at the best of times.

**Comment by tschmidty69** [comment]
OK, so this was easier than I figured. I do need to keep tweaking, I'd like to add client certs one guy requested and TLS support. Someone will probably request publishing messages but I am ok with leaving that! I did play and was able to set up a standalone app. One thing that would be good is avoiding the need to define the lat, log. elev. timezone and allow defaults if not using hass. Simply printing a big warning on those should be ok.

**Comment by acockburn** [comment]
Is this ready to be merged yet? You said you were going to vcontinue working on it?

**Comment by uchagani** [comment]
FYI, I've tested the code in this PR inside the `custom_plugins` dir in `v3` and it works great.

**Comment by tschmidty69** [comment]
I added the options to enable a client certificate but have not had a chance to test it (and forgot to merge), but otherwise the plugin works great. I enabled a standalone app that worked well with it which was really nice! So I would say yes, it's ready to merge and I will reach out to 'client cert guy' and see if it will work for him.

**Comment by uchagani** [comment]
@acockburn the plugin gets loaded correctly but you can't use the plugin in an app.  My guess is that appdaemon is not reading the `custom_plugins` dir.

error:

```bash
    import appdaemon.plugins.mqtt.mqttapi as mqtt
ModuleNotFoundError: No module named 'appdaemon.plugins.mqtt'
```

**Comment by tschmidty69** [comment]
It reads it but doesn't seem to get it into the module space. Not familiar enough to know and haven't had time to poke

**Comment by uchagani** [comment]
I have a suggestion:  instead of firing a generic `MQTT_MESSAGE`, we should make the event name the `topic`.  That way apps that are using the plugin can listen for only the event that they are interested in.

Currently:

```python
def initialize(self):
  self.log("__function__: MQTT DEMO Listening")
  self.listen_event(self.mqtt_message,'MQTT_MESSAGE')
```

Suggestion:

```python
def initialize(self):
  self.log("__function__: MQTT DEMO Listening")
  self.listen_event(self.mqtt_message,'some/topic/i/am/interested/in')
```

**Comment by tschmidty69** [comment]
Hmm, i could see that working but a couple things come to mind. By convention every event is upper case, discrete and the data is in a data parameter, And the bigger thing is you don't necessarily know what topics you want to listen for, and if you look at the way appdaemon event listener works, you can't do a wildcard listen. So I don't think it would work in practice.  For example I have one core app that listens for the events and compares them to intents that various sub apps have registered and calls callbacks as needed. I can think of different ways to make that work and none of them are really wrong except that they are outside the conventions.

 For instance HASS  fires a SERVICE_CALL event with everything else in data, so it would seem to make sense to follow a similar model, unless there was a huge reason not to. 

@acockburn any thoughts?

**Comment by uchagani** [comment]
You could subscribe to all events by not passing in an event name.

**Comment by smurfix** [comment]
+1 on the "subscribe to all events by not passing in an event name" idea.

**Comment by acockburn** [comment]
Lots of great discussion here - I want this to be as functional as possible when I merge it, so I'll hold off for now until things settle down, to make it easier for you to continue making changes.

**Comment by uchagani** [comment]
@acockburn do you have an opinion on how the events should be structured based on the comments above?

**Comment by uchagani** [comment]
From my perspective, everything in MQTT is an message so the convention of a generic MQTT_MESSAGE shouldn't apply.  In HASS, we have different events (service calls, etc) but in MQTT everything will be the same event.  which means that anyone that uses the MQTT plugin will need to parse every single message that comes down.

If i configure the MQTT plugin to subscribe to 5 topics, and I want 5 different AppDaemon apps (one to handle each topic), I have to parse all the messages 5 times or code one single app to parse the messages and then send them to the appropriate app.  

Where as if we make the event name the name of the topic itself, apps can subscribe to just the topic that they care about and no generic parsing is needed.

**Comment by acockburn** [comment]
It's currently possible in AD to filter events based on the arguments in them. I don;t remember the exact format of the Event this plugin hands to AD, but something like this should work:

```python
def initialize(self):
  self.listen_event(self.mqtt_message,topic='some/topic/i/am/interested/in')
```

All this would require is that the event has a parameter named `topic` and AD would automatically filter using existing functionality.

**Comment by uchagani** [comment]
That would work for me! I'll test it out this evening.

**Comment by acockburn** [comment]
Docs are here:

http://appdaemon.readthedocs.io/en/latest/APIREFERENCE.html#listen-event

**Comment by uchagani** [comment]
Will this work even in the case of a string message?

**Comment by acockburn** [comment]
Not sure what you mean

**Comment by uchagani** [comment]
Right now the data portion of the mqtt message is a string and not a dict

**Comment by tschmidty69** [comment]
data is a dict containing topic and payload

**Comment by uchagani** [comment]
Ah ok. thanks for the correction. This would work for me then.

**Comment by tschmidty69** [comment]
@acockburn Poking to see if you can take a look again, I think we are all set.

**Comment by acockburn** [comment]
Ok, I'll get this into the next release.

**Comment by tschmidty69** [comment]
Thanks, added some options for verification of tls on the broker. Nothing show stopping.

**Comment by uchagani** [comment]
@acockburn any way we can avoid logging for state for plugins that don't carry state?  For example I see this log-line every 10 second:

```
2018-04-17 00:35:49.563050 INFO AppDaemon: MQTT: get_complete_state: None ***
```

not a big deal just wondering.

**Comment by rsdatatechnologies** [comment]
Hi Everyone, 

I've attempted using this plugin today and found some issues.

Firstly I can confirm the issue mentioned by @uchagani and @tschmidty69 regarding the custom_plugins feature. The plugin is initialized but is not available in the app. 

After placing it in the plugins folder and installing I found that it would not trigger the `mqtt_on_connect()` method. To remedy this I simply placed the `self.mqtt_client.loop_start()
` bellow the `self.mqtt_client.connect_async` call and it connected successfully to my server and the plugin was able to receive and log message.

Now I have messages logged from the plugin but these events are not captured by the event listener in the app. I am using the exact app as in the sample above. If anyone can point out the mistake(s) I'm making that would be great ;)

Also: 

` self.log('INFO',"on_connect: connected: {}".format(rc)) ` (line 77)

Should be:

`self.log("MQTT on_connect: connected: {}".format(rc),level='INFO')`

**Comment by tschmidty69** [comment]
You took out the jarvis stuff right? Sorry that was specific to what I was doing. But you are saying mqtt_demo never logs anything? Can you post the full log messages with appdaemon logging info?

**Comment by rsdatatechnologies** [comment]
Yes, I did take out the Jarvis stuff. 

Yeah the mqtt_demo definitely initializes. According to my debug logs, the listen_event for the app is called but nothing in the log from the mqtt_demo app. 

[log.log](https://github.com/home-assistant/appdaemon/files/1940479/log.log)
[mqtt_demo.txt](https://github.com/home-assistant/appdaemon/files/1940482/mqtt_demo.txt)

I a few modifications which included:

- adding lwt 
- adding a publish method
- publish on connect

These changes were made after I discovered the problem so I highly doubt they are the cause of my problem.

[appdaemon.txt](https://github.com/home-assistant/appdaemon/files/1940483/appdaemon.txt)
[mqttplugin.txt](https://github.com/home-assistant/appdaemon/files/1940486/mqttplugin.txt)

**Comment by tschmidty69** [comment]
What's so wrong with pull requests? And tha tis the whole point of custom_plugins

**Comment by rsdatatechnologies** [comment]
There is nothing wrong with pull requests. But I don't think a pull request on the appdaemon repo is necessary, it ought to be on a mqtt_plugin repo. This would allow faster and more effective development, especially as more modules start coming into the picture.

**Comment by tschmidty69** [comment]
If you are calling state_update in on_connect then use the same syntax as I have under the on_message.

**Comment by tschmidty69** [comment]
But honestly I don't think that was the issue since it was connecting and getting the mqtt messages in. But since you seem to have a lot of moving pieces.

**Comment by rsdatatechnologies** [comment]
I don't doubt your honesty. But as far as I know an async function `self.AD.state_update` cannot be called from a non-async function, it must be called from an event loop. Does your code works perfectly on your side? What is your python version?


Here is the link to my working fork: https://gitlab.com/rsdatatechnologies/custom_appdaemon

**Comment by tschmidty69** [comment]
Arg, you are absolutely right. Apparently in one of my commits I deleted the async fix from on_message. Take a look, essentially just grab the look and run it as coroutine_threadsafe

**Comment by tschmidty69** [comment]
And FWIW, I agree about the mqtt_client, I'll change that to mqtt. I do want to keep a prefix simply because it makes it easier to read when combined with other apps in a yaml file.

**Comment by rsdatatechnologies** [comment]
@tschmidty69  Glad to help ;)

**Comment by uchagani** [comment]
@acockburn any idea when this will be merged in?

**Comment by uchagani** [comment]
@tschmidty69 the username and password stuff you added make are required to be set?  what if we don't have a username and password?

right now i'm getting an encoding error because my config looks like this:

```yaml
    MQTT:
      type: mqtt
      verbose: True
      mqtt_client_host: 127.0.0.1
      mqtt_client_port: 1883
      mqtt_client_topics:
        - hermes/intent/#
```

**Comment by Odianosen25** [comment]
@uchagani, you can try using my plugin update here #303. You din't need it to be set.

**Comment by tschmidty69** [comment]
@uchagani you shouldn't need it set but it doesn't matter anyway, I've given up on dude ever merging this.

**Comment by acockburn** [comment]
I've been slammed at work for the last 2-3 months, and this plugin seems to have been changing on a regular basis - I still want this as part of the AD ecosystem either as an included base plugin or a separately maintained custom component - I believe it adds a lot of value.

How would you like to see this go?

**Comment by tschmidty69** [comment]
@acockburn It isn't changing much since it supports what people have asked for. I'd prefer to just merge it and deal with issues as they come up rather than holding the whole thing back.

**Comment by acockburn** [comment]
OK, I'll get this into the next release :)

**Comment by foxy82** [comment]
Hi,is there any news on when this will be released?

**Comment by simonvanderveldt** [comment]
Would this allow one to use AppDaemon without using Home Assistant?

**Comment by uchagani** [comment]
You can already use Appdaemon without home assistant

**Comment by tschmidty69** [comment]
Yes, that is the idea. You already can use it without HA, this just allows you to use MQTT events which can come from a lot of sources.

**Comment by acockburn** [comment]
As yoou can see I finally merged this - it will be in the upcoming 3.0.2 - sorry for the delay.

I also merged the changes Odianosen has been working on - there shouldn;t be any breaking changes. The merged version is available in the dev branch if you want to test it.

**Comment by Odianosen25** [comment]
Well the only potential breaking change, depending on how the system is used, is in setting up the plugin instance.

In your original cod, you had the config as `mqtt_client_host`, `mqtt_client_port` and the likes. These have been changed to `client_host`, `client_port` and so on without the `mqtt_` prefix.

Outside the above, I don't think there should be any difference.

Regards

**Comment by Odianosen25** [comment]
Well the only potential breaking change, depending on how the system is used, is in setting up the plugin instance.

In your original cod, you had the config as `mqtt_client_host`, `mqtt_client_port` and the likes. These have been changed to `client_host`, `client_port` and so on without the `mqtt_` prefix.

Outside the above, I don't think there should be any difference.

Regards

**Comment by Odianosen25** [comment]
Well the only potential breaking change, depending on how the system is used, is in setting up the plugin instance.

In your original cod, you had the config as `mqtt_client_host`, `mqtt_client_port` and the likes. These have been changed to `client_host`, `client_port` and so on without the `mqtt_` prefix.

Outside the above, I don't think there should be any difference.

Regards

**Pull request merged**
