### PR TITLE
Code reformatting and some fixes

### LINKED ISSUE #32: 1.5.1 Doesn't like Dev
Looks like the new version pull/check doesn't account for someone running a dev build of HASS.  Not sure the best way to handle the fix since you want to check against the version to determine whether or not to use websockets.

```bash
2017-01-30 08:51:47.626748 INFO AppDaemon Version 1.5.1 starting

Traceback (most recent call last):
File "/usr/local/bin/appdaemon", line 11, in <module>
load_entry_point('appdaemon==1.5.1', 'console_scripts', 'appdaemon')()
File "/usr/local/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1250, in main
conf.version = int(ha_config["version"].replace(".", ""))

ValueError: invalid literal for int() with base 10: '0380dev0
```

### PR DESCRIPTION
**Pull request by yawor**
Hi

As discussed in #27, I've reformatted the code to be PEP8 compliant (or almost compliant).
The PR also fixes some issues I've found looking around the code.

I've also fixed #32 by using setuptools parse_version function, to properly parse and compare HASS version number.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @yawor, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#33).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by acockburn** [comment]
Thanks for this - I appreciate your thorough work :)

Can I ask you to edit the PR so it comes in against the new PEP8 branch I have created? I'll be wanting to run some local tests before I merge it with the master branch.

Also, before I can do the merge, Home Assistant mgmt require that you sign the CLA as per the message above.

Thanks again!

**Comment by yawor** [comment]
OK I've changed it to use new branch as a base. I've already signed CLA right after submitting the PR.

**Comment by acockburn** [comment]
Excellent - thanks. I'll work through this and let you know if I have any questions.

**Comment by yawor** [comment]
I'll be happy to answer any questions. As you can't really compare the code before and after reformatting (too much of a difference for diff to work) here's a summary of things I've done in the first commit in this PR:

- Changed indentation to use 4 spaces per level instead of 2.
- All lines split in a way that now all are at most 79 characters long.
- When dict with many keys is used in a function call I've split it into multiple lines for better readability of what is actually being passed to the function.
- All equality and inequality check operations on None, True and False changed to identity check operator. For example `foo == None` became `foo is None` and `bar != False` became `bar is not False`.
- I've not changed any logic in the code reformatting. Any other changes are in separate commits.

**Comment by acockburn** [comment]
All looks good, I understand the changes and learned a few things in the process :)

I'll run this at home for a few days but I am not expecting any issues - I'll roll out the next version with these changes probably at the weekend.

Thanks again for your thorough review.

**Pull request merged**
