### PR TITLE
Climate widget - take configuration step into consideration

### PR DESCRIPTION
**Pull request by mad-ady**
The relevant commit is this: https://github.com/home-assistant/appdaemon/commit/6ad539593e3f5296954b3629d570f1b17b59797b

Not sure how I got the other ones, probably a mistake I did when syncing repos...

### CODE REVIEW

**Comment by mad-ady** [comment]
This also contains a commit to allow date format in the clock widget to be customized (fixes #187)

**Comment by acockburn** [comment]
Thanks!

**Comment by acockburn** [comment]
Looks good - I'll merge this into the next 3.0 beta.

**Comment by mad-ady** [comment]
Thanks!

**Pull request merged**
