### PR TITLE
Fix bug when using oneshot callbacks

### PR DESCRIPTION
**Pull request by petersohn**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @petersohn, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#299).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ConnorGriffin** [comment]
Does this fix the issue where when using listen_state with oneshot=True you get a KeyError: 'handle' ? 

```
2018-06-23 15:52:33.153030 WARNING AppDaemon: ------------------------------------------------------------
2018-06-23 15:53:02.044645 WARNING AppDaemon: ------------------------------------------------------------
2018-06-23 15:53:02.045759 WARNING AppDaemon: Unexpected error during state_update()
2018-06-23 15:53:02.047933 WARNING AppDaemon: ------------------------------------------------------------
2018-06-23 15:53:02.050377 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2333, in state_update
    self.process_state_change(namespace, data)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2309, in process_state_change
    removes.append({"name": callback["name"], "uuid": callback["kwargs"]["handle"]})
KeyError: 'handle'
```

**Comment by acockburn** [comment]
I couldn't reproduce the  issue when I tested. - I'm also not sure what the code changes even do ... I do remember fixing an indentation issue in this piece of the code which may have had a similar effect, although an else clause that does nothing is the same as not having one at all as far as I can see.

I'll close this for now, but take another look if someone manages to reproduce the issue in version 3.0.2 or later after I release it.

**Comment by Swamp-Ig** [comment]
Yeh it's fixed, all good.

**Pull request closed without merging**
