### PR TITLE
Update INSTALL.rst

### PR DESCRIPTION
**Pull request by spacemanspiff2007**
added info how to add api_password in configuration.yaml

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @spacemanspiff2007, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#377).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by spacemanspiff2007** [comment]
I signed the CLA but it seems to be hanging.
Can you please help me?

**Comment by spacemanspiff2007** [comment]
cla-bot seems to still be stuck. Can anyone help?

**Comment by acockburn** [comment]
The latest version of AD will include the new auth scheme via Long Lived Access Tokens so I am closing this.

**Pull request closed without merging**
