### PR TITLE
Update MQTT_API_REFERENCE.rst

### PR DESCRIPTION
**Pull request by u17194907425**
It looks like the section needs an update keeping in mind the stahe of the embedded MQTT broker of HA.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @u17194907425, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#578).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ReneTode** [comment]
@u17194907425 i think you confused the appdaemon docs with the homeassistant docs.

the mqtt plugin isnt specific for home assistant mqtt, but general for all mqtt
and you added a home assistant automation which has nothing to do with appdaemon.

so this change wont be added

**Comment by u17194907425** [comment]
I get you. So maybe I need to change the message somehow. See, the reason I proposed the change was because the code in the examples isn't working out of the box in HA. I mean this → https://appdaemon.readthedocs.io/en/3.0.4/MQTT_API_REFERENCE.html#id18

You know the topic → https://community.home-assistant.io/t/appdaemon-mqtt/8118/21

Yeah I know it is not HA-specific but... maybe at least a small mention can be put into the doc. When I was doing my 1st steps in using AD for MQTT it could have saved me a lot of time.

**Comment by Odianosen25** [comment]
@u17194907425,

As outlined by @ReneTode, this will not be added, so will be kindly closing this issue.

Please reopen if more information that you think needs reconsidering it available.

Regards

**Comment by u17194907425** [comment]
Okay, thank you for your cooperation

**Comment by ReneTode** [comment]
@u17194907425 the code should work as in the examples and is 100% independant from Home assistant.
the forum topic you refer to is very old and outdated.

if you have any questions why it doesnt work as in the docs, then please visit our discord and ask questions there.

**Comment by u17194907425** [comment]
@ReneTode actually that comment was the push I needed. The configuration section of the manual gave me a bit more help and finally I've found myself here https://community.home-assistant.io/t/announcement-appdaemon-3-0-2/76155/19

Now back to the pull request. How about at least adding a reference in MQTT API section to the configuration of the plugin. I'd also like to fill out an empty space on the Config because right now this part is empty here https://appdaemon.readthedocs.io/en/3.0.4/CONFIGURE.html#configuration-of-the-mqtt-plugin

_An example of the MQTT plugin could look like the following:_ ... and then nothing

Will you decline this kind of pull request as well?

**Comment by ReneTode** [comment]
in the docs there is clearly stated what plugins are for. (in the sections about plugin and plugin configuration and in the section how to build apps)
so there is no need to say in the mqtt api part that you need the mqtt plugin.

but indeed an example should be there.
we cant update the docs from an older version, doc updates always follow the version updates.
and in the dev version there is already an example ;) 

so if you want to change or add something then first check in the dev version if its already done.
https://appdaemon.readthedocs.io/en/dev/index.html

i think that if you take a look at the dev docs, you will notice that a lot is going to change.
and if you notice something wrong there, please feel free to make another PR.

and if you have any questions I am always there on discord 
https://discord.gg/pHsjADY

im not checking up that much on the forum lately, because it all was growing above my head, but on discord you will get a quite quick response from me. 

and just to make it clear again, the only reason why the PR was declined is because the info you gave was wrong. the plugin API works with every mqtt broker, and never needs anything in homeassistant.

i know from at least 1 person who uses appdaemon with only the mqtt plugin, completely without having home assistant installed.

**Pull request closed without merging**
