### PR TITLE
Handle requests from Apiai

### PR DESCRIPTION
**Pull request by engrbm87**
I am using apiai with home-assistant for google voice actions. i was so happy when i saw that appdaemon can now handle requests from alexa as apiai is very similar. I added the functions for Apiai based on the ones for Alexa and successfully tested it with Api.ai

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @engrbm87, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#115).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by acockburn** [comment]
This is cool thanks - I thought I was going to have to buy a Google Home to work on this :) I probably still will anyway!

I'll get this into the next release.

**Comment by acockburn** [comment]
Could you provide a sample App using the calls please? For the docs.

**Comment by acockburn** [comment]
Great - thanks!

**Pull request merged**
