### PR TITLE
basedisplay updates and weather_summary, london_underground widgets

### PR DESCRIPTION
**Pull request by mmmmmtasty**
Introduces a new widget that displays an icon and the state text summary of the dark sky summary sensors:

 - sensor.dark_sky_hourly_summary
 - sensor.dark_sky_daily_summary
 - sensor.dark_sky_summary

This is because I wanted the weather to be able to fit in a header rather than requiring such a large widget as the original weather one.

As part of this though - I did wonder if updating the basedisplay module to understand and accept attributes as the state_text rather than just 'state.state' might remove the need for extra widgets like this anyway....

### CODE REVIEW

**Comment by mmmmmtasty** [comment]
I had a brain wave and I can actually do this without introducing a new base widget by making non-breaking changes to basedisplay. I will update this PR

**Comment by acockburn** [comment]
Thanks for this :) I;m in the middle of a major refactor at the moment but I'll get this in as soon as things have stabilized.

**Comment by mmmmmtasty** [comment]
I guessed so, I'm still a couple of commits away from this being complete - I'm wrestling with the state_map currently :)

**Comment by mmmmmtasty** [comment]
Ooooh - question though.... does you refactor include the widgets themselves? Just want to know before I spend too much time working through them ;)

**Comment by acockburn** [comment]
No, the widget and dashboard creation code are unaffected so no worries ;)

**Comment by mmmmmtasty** [comment]
Looks like I accidentally committed a new line at the end of dashboard.js, but this PR is ready to go :)

**Comment by mmmmmtasty** [comment]
As discussed there is a more flexible way of doing exactly what I have done in this PR. I will update it again this weekend to reflect that.

**Pull request merged**
