### PR TITLE
Merge pull request #2 from home-assistant/appdash

### PR DESCRIPTION
**Pull request by indy55**
Appdash

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @indy55, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#51).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @indy55, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#51).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by acockburn** [comment]
Not sure what you are trying to do here but I am not accepting PRs against this branch.

**Comment by indy55** [comment]
Sorry about that, please disregard

**Comment by acockburn** [comment]
OK, no worries.

**Pull request closed without merging**
