### PR TITLE
Testers wanted | Docker Python 3.8

### PR DESCRIPTION
**Pull request by benleb**
With the apps I use, it works without problems. But due to the nature of appdaemon, more testing is needed! So lets go ;)

### CODE REVIEW

**Comment by ReneTode** [comment]
thx for testing, but im not sure if it is a good idea to set the docker version to 3.8 when the developers are not working with 3.8

nothing wrong with everyone doing it for themselves though.

**Comment by benleb** [comment]
Yes, as mentioned this should not be merged now but encourage users like you to try if it works for you too and maybe tell us about ;)

**Comment by dlashua** [comment]
@benleb  thanks for this! I didn't even know Python 3.8 was released.

I built a new docker image using your 3.8 Dockerfile and have loaded it in to my production AppDaemon instance. It loaded all of my apps and they have run, so far, without issue.

**Comment by Odianosen25** [comment]
Will try it out when next I upgrade my docker image

**Comment by acockburn** [comment]
I'll momnitor this issue - when enough people report success we can merge - thanks @benleb, you are helping out a lot at the moment :)

**Comment by Odianosen25** [comment]
Migrated to using python 3.8 and can confirm all works fine. For now :)

**Comment by grewhit25** [comment]
I also migrated successfully to python 3.8 on my Raspberry Pi3b.
I did pull the dev branch in my Dockerfile, with the following snippet:

```yaml
FROM python:3.8-alpine
fetch hhttp://dl-cdn.alpinelinux.org/alpine/v3.10/main/armv7

AppDaemon Version 4.0.0 starting

My previous version 4b2
```
Hope this helps.

**Comment by Odianosen25** [comment]
Well I lost admin UI when using 3.8 and had to revert back to get it to work.

Also lots of depreciation warnings. So I think we should wait for a while before merging officially.

Regards

**Comment by dlashua** [comment]
@Odianosen25 I have the same issue as I'm noticing this morning. Admin UI no longer loads.

Also, let me know what you find about create_task.

**Comment by Odianosen25** [comment]
@dlashua,

The admin UI issue, I think has got to do with the aiohttp module, which needs to be updated to support 3.8.

The create_task issue, I still don’t know why yet. There are lots of asyncio updates to 3.8, and might use be one of them; as I haven’t really tried so much. But strange things is, even asyncio itself has some issues, which I don’t get why. 

Regards

**Comment by Odianosen25** [comment]
```
/usr/local/lib/python3.8/site-packages/future/standard_library/__init__.py:65: DeprecationWarning:,
,
the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses,
,
/usr/local/lib/python3.8/asyncio/events.py:81: DeprecationWarning:,
,
The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.,
,
/usr/local/lib/python3.8/site-packages/psutil/_pslinux.py:1221: RuntimeWarning:,
,
ignoring OSError(61, 'No data available') for file '/sys/class/hwmon/hwmon2/temp1_input',
,
/usr/local/lib/python3.8/site-packages/aiohttp/connector.py:840: DeprecationWarning:,
,
The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.,
,
/config/apps/zigbee/zigbee_command.py:11: RuntimeWarning:,
,
coroutine 'ZigbeeCMD.register_app_services' was never awaited,
,
```

`'ZigbeeCMD.register_app_services'` is my function, and that error doesn't show up in 3.7

```
/usr/local/lib/python3.8/site-packages/appdaemon/__main__.py:134: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead,
  pending = asyncio.Task.all_tasks(),
/usr/local/lib/python3.8/site-packages/aiohttp/connector.py:840: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.,
  hosts = await asyncio.shield(self._resolve_host(,
/usr/local/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.,
  self._context.run(self._callback, *self._args),
/usr/local/lib/python3.8/site-packages/future/standard_library/__init__.py:65: DeprecationWarning:,
,
the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses,
,
/usr/local/lib/python3.8/asyncio/events.py:81: DeprecationWarning:,
,
The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.,
,
/usr/local/lib/python3.8/site-packages/psutil/_pslinux.py:1221: RuntimeWarning:,
,
ignoring OSError(61, 'No data available') for file '/sys/class/hwmon/hwmon2/temp1_input',
,
/usr/local/lib/python3.8/site-packages/aiohttp/connector.py:840: DeprecationWarning:,
,
The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.,
,
```
In all, I think 3.8 still need some testing, as I don't get how asyncio which is standard module gives some warning messages

**Comment by Odianosen25** [comment]
@benleb, 

I have carried out some tests with 3.8, and submitted a PR for it. If you don't mind will be closing this one.

Regards

**Pull request closed without merging**
