### PR TITLE
Raspian patch

### PR DESCRIPTION
**Pull request by mike-goldfinger**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mike-goldfinger, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#825).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by benleb** [comment]
?! whats the idea of this PR, besides breaking every existing setup?!

**Comment by mike-goldfinger** [comment]
Sorry for this false merge request. I've messed up pull/push requests from my personal git repo witch I have for education. 
I never wanted to push or merge anything into the official home-assistant repository. 
In my opinion I've canceled my false request. I've not, please cancel it or let me know if I need to cancel it otherwise.

**Comment by benleb** [comment]
no problem :) was just curious 😅

**Pull request closed without merging**
