### PR TITLE
Update TUTORIAL.md

### PR DESCRIPTION
**Pull request by smolz**
minor spelling

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @smolz, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;appdaemon#34).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by acockburn** [comment]
Hi there - can you point out what you actually changed? I can;t see any differences when comparing the files.

**Comment by yawor** [comment]
I think it's in this sentence:

> We tell AppDaemon that we are only interested in state **changesd** where

I couldn't find any other differences.

**Comment by smolz** [comment]
that is correct.  I apologize, i should be much more explicit in my requests.

**Pull request merged**
