### PR TITLE
Yaml loading fix/cleanup

### PR DESCRIPTION
**Pull request by rschaeuble**
While working on #305 I found an error in logging YAML parsing errors.

I have fixed these, and also removed some small code duplication around parsing YAML files and handling errors.

### CODE REVIEW

**Comment by rschaeuble** [comment]
I honestly have no idea why Travis CI is trying to build this as a Ruby project...
@acockburn any ideas what's going on here with Travis?

**Comment by rschaeuble** [comment]
@acockburn: any chance you could have a look at the Travis failure? Or maybe just trigger a rebuild?

Also, as my pull requests are nearly half a year old by now, I wonder if you're interested in them at all.

**Comment by acockburn** [comment]
I've been away from AppDaemon for the last 6 months due to work and an injury, but I am back on the case now. I have been working through the backlog of PRs and will be getting to yours soon - I do intend to merge it and I thanks you for it. I just kicked off the tests again - we'll see what happens and if necessary I'll have someone fix it.

**Comment by rschaeuble** [comment]
I'm glad that you're back and development of AppDaemon has resumed :)

**Comment by acockburn** [comment]
OK, having reviewed both PRs, this one is redundant as all the commits are included in the later PR, so I will close this without merging, and merge the other.

**Pull request closed without merging**
