### PR TITLE
Modified `immediate` Flag in Listen_state

### PR DESCRIPTION
**Pull request by Odianosen25**
Expanded on the ability to allow for when listening to state changes, the callback function can be ran immediately to allow for the function to be ran at startup.

The following are possible:
- If `duration` is not specified, the callback is ran immediately. If specified, it will be ran after the specified `duration`
- If `new` is specified, it will only run the callback, if the present `state` is the `new` state

Regards

### CODE REVIEW

**Comment by ReneTode** [comment]
please check for typos

**Comment by Odianosen25** [comment]
Done that :) thanks

**Comment by ReneTode** [comment]
If ``new`` and ``duration``is not set should be
If ``new`` and ``duration`` are not set

**Comment by Odianosen25** [comment]
Fixed thanks

**Pull request merged**
