### PR TITLE
Upgraded the baseweather widget

### PR DESCRIPTION
**Pull request by kabturek**
* added the ability to change the sensors used
* added dynamic units for more sensors
* added option for showing forecast (show_forecast: 1)
* added icons for conditions (prefer_icons: 1)
* added the option to show Rain/Snow depending on precip_type sensor (and change icons)
* wind icon rotates acording to wind bearing

There are some css changes (used 4 spaces instead of tabs).
Had to remove the indentions from the html file to get rid of those ugly spaces between display-block elements.

### CODE REVIEW

**Comment by kabturek** [comment]
closed https://github.com/home-assistant/appdaemon/pull/270 and recreated to make sure cla-bot it happy

**Comment by acockburn** [comment]
Looks great - thanks!

**Comment by acockburn** [comment]
Hi there - 

When I added the forecast to my dark sky config in HASS, I got many of the forcast sensors, but `sensor.dark_sky_temperature_1` and `sensor.dark_sky_apparent_temperature_1` were not among them, which obviously breaks the forecast funtionality of the widget. Are yo uaware of anything special I need to do to get these fields?

**Comment by kabturek** [comment]
yes - sorry - good catch: i was testing with other weather and indeed when i initially set up darksky those were missing in but added some template sensors with those names with the intention of going back when i get it working. 
And of course I forgot. 
There should be min/max instead of temperature/apparent_temperature as darksky doesn't provide  temperature/apparent_temperature for forecast. I've opened #284 with the necessary changes.

**Comment by acockburn** [comment]
Cool - thanks :)

**Pull request merged**
